config/routes.rb
Antragsportal::Application.routes.draw do
  root :to => 'motions#search'
  
  resources :projects

  resources :votes

  resources :decisions

  resources :tags

  resources :motions
  
  resources :users, only: [:new, :create]
  
  get "/projectmotions/:id" => "projects#projectmotions"
  get "search" => "motions#search"
  post "search" => "motions#searchresult"

  

end

app/models/decision.rb
class Decision < ActiveRecord::Base
  has_many :votes
  belongs_to :motions
  attr_accessible :commitee_date, :commitee_name, :id, :motion_id, :text, :vote_id
end

app/controllers/decisions_controller.rb
class DecisionsController < ApplicationController
  # GET /decisions
  # GET /decisions.json
  def index
    @decisions = Decision.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @decisions }
    end
  end

  # GET /decisions/1
  # GET /decisions/1.json
  def show
    @decision = Decision.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @decision }
    end
  end

  # GET /decisions/new
  # GET /decisions/new.json
  def new
    @decision = Decision.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @decision }
    end
  end

  # GET /decisions/1/edit
  def edit
    @decision = Decision.find(params[:id])
  end

  # POST /decisions
  # POST /decisions.json
  def create
    @decision = Decision.new(params[:decision])

    respond_to do |format|
      if @decision.save
        format.html { redirect_to @decision, notice: 'Decision was successfully created.' }
        format.json { render json: @decision, status: :created, location: @decision }
      else
        format.html { render action: "new" }
        format.json { render json: @decision.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /decisions/1
  # PUT /decisions/1.json
  def update
    @decision = Decision.find(params[:id])

    respond_to do |format|
      if @decision.update_attributes(params[:decision])
        format.html { redirect_to @decision, notice: 'Decision was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @decision.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /decisions/1
  # DELETE /decisions/1.json
  def destroy
    @decision = Decision.find(params[:id])
    @decision.destroy

    respond_to do |format|
      format.html { redirect_to decisions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/decisions_helper.rb
module DecisionsHelper

end

app/views/decisions/_form.html.erb
<%= form_for(@decision) do |f| %>
  <% if @decision.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@decision.errors.count, "error") %> prohibited this decision from being saved:</h2>

      <ul>
      <% @decision.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :vote_id %><br />
    <%= f.number_field :vote_id %>
  </div>

  <div class="field">
    <%= f.label :motion_id , "Antragsnummer: "%><br />
    <%= f.select :motion_id, Motion.all.map {|m| [m.register,m.id]} %>
  </div>
  <div class="field">
    <%= f.label :text, "Abgestimmter Antragstext:" %><br />
    <%= f.text_area :text %>
  </div>
  <div class="field">
    <%= f.label :commitee_name, "Ausschussname:" %><br />
    <%= f.select :commitee_name, ["Bauausschuss","Sozialausschuss","Hauptausschuss","Stadtverordnetenversammlung"]%>
  </div>
  <div class="field">
    <%= f.label :commitee_date, "Ausschussdatum:" %><br />
    <%= f.date_select :commitee_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/decisions/edit.html.erb
<h1>Editing decision</h1>

<%= render 'form' %>

<%= link_to 'Show', @decision %> |
<%= link_to 'Back', decisions_path %>

app/views/decisions/index.html.erb
<h1>Anzeige aller Entscheidungen</h1>

<table class="table table-striped">
  <tr>
    <th>Aktenzeichenn:</th>
    <th>Antragstitel:</th>
    <th>Ausschuss:</th>
    <th>Entscheidungsdatum:</th>
    <th></th>
    <th></th>
  </tr>

<% @decisions.each do |decision| %>

	
  <tr>
    <td><%= Motion.find(decision.motion_id).register %></td>
    <td><%= Motion.find(decision.motion_id).title %></td>
    <td><%= decision.commitee_name %></td>
    <td><%= decision.commitee_date.strftime('%d.%m.%Y') %></td>
    <td><%= link_to 'Bearbeiten', edit_decision_path(decision), :class => "btn btn-mini" %></td>
    <td><%= link_to 'Löschen', decision, method: :delete, :class => "btn btn-mini btn-danger" %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Neue Entscheidung', new_decision_path %>

app/views/decisions/new.html.erb
<h1>Neue Entscheidung hinzufügen</h1>

<%= render 'form' %>

<%= link_to 'Back', decisions_path %>

app/views/decisions/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <b>Motion:</b>
  <%= @decision.motion_id %>
</p>

<p>
  <b>Text:</b>
  <%= @decision.text %>
</p>

<p>
  <b>Ausschussname:</b>
  <%= @decision.commitee_name %>
</p>

<p>
  <b>Ausschussdatum:</b>
  <%= @decision.commitee_date.strftime('%d.%m.%Y') %>
</p>


<%= link_to 'Bearbeiten', edit_decision_path(@decision) %> |
<%= link_to 'Zurück zur Übersicht', decisions_path %>