config/routes.rb
Antragsportal::Application.routes.draw do
  root :to => 'motions#search'
  
  resources :projects

  resources :votes

  resources :decisions

  resources :tags

  resources :motions
  
  resources :users, only: [:new, :create]
  
  get "/projectmotions/:id" => "projects#projectmotions"
  get "search" => "motions#search"
  post "search" => "motions#searchresult"

  

end

app/models/motion.rb
class Motion < ActiveRecord::Base
  has_and_belongs_to_many :projects
  has_many :decisions
  has_many :tags
  attr_accessible :date, :latitude, :longitude, :register, :text, :title
end

app/controllers/motions_controller.rb
class MotionsController < ApplicationController
  def search
    
  end
  
  # GET /motions
  # GET /motions.json
  def index
    @motions = Motion.all
    
    
    ####### FEHLER!!!!!!!!
    ####### FEHLER!!!!!!!!####### FEHLER!!!!!!!!####### FEHLER!!!!!!!!####### FEHLER!!!!!!!!####### FEHLER!!!!!!!!####### FEHLER!!!!!!!!
    
    @tags = Tag.where("motion_id= ?",1)
    

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @motions }
    end
  end

  # GET /motions/1
  # GET /motions/1.json
  def show
    @motion = Motion.find(params[:id])
    
    #Besorgt sich alle passenden Tags zum Antrag
    @tags = Tag.where("motion_id= ?",params[:id])
    
    #Besorgt sich alle passenden Projekte zum Antrag
    @projects = Motion.find(params[:id]).projects

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @motion }
    end
  end

  # GET /motions/new
  # GET /motions/new.json
  def new
    @motion = Motion.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @motion }
    end
  end

  # GET /motions/1/edit
  def edit
    @motion = Motion.find(params[:id])
  end

  # POST /motions
  # POST /motions.json
  def create
    @motion = Motion.new(params[:motion])

    respond_to do |format|
      if @motion.save
        format.html { redirect_to @motion, notice: 'Motion was successfully created.' }
        format.json { render json: @motion, status: :created, location: @motion }
      else
        format.html { render action: "new" }
        format.json { render json: @motion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /motions/1
  # PUT /motions/1.json
  def update
    @motion = Motion.find(params[:id])

    respond_to do |format|
      if @motion.update_attributes(params[:motion])
        format.html { redirect_to @motion, notice: 'Motion was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @motion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /motions/1
  # DELETE /motions/1.json
  def destroy
    @motion = Motion.find(params[:id])
    @motion.destroy
    
    # Löscht zum passenden Antrag auch alle Entscheidungen
    @decisions = Decision.where("motion_id =?",params[:id])
    @decisions.each do |decision|
      decision.destroy
    end
    
    #Löscht zum passenden Antrag auch alle zugehörigen Tags
    @tags = Tag.where("motion_id =?",params[:id])
    @tags.each do |tag|
      tag.destroy
    end

    respond_to do |format|
      format.html { redirect_to motions_url }
      format.json { head :no_content }
    end
  end
  
  def search
  end
  
  def searchresult
    # Funktion ermöglicht das Suchen nach Anträgen
  end
  
  def showonemotion
    @motion = Motion.find(1)
  end
end

app/helpers/motions_helper.rb
module MotionsHelper
  
  # Dient zur Anzeige eines Antrags auf einer Karte
  def show_motion_on_map (motion)

        #Berechnet den Ausschnitt
        firstlat = motion.latitude.to_f - 0.003311
        secondlat = motion.latitude.to_f + 0.003191
        firstlon = motion.longitude.to_f - 0.05594
        secondlon = motion.longitude.to_f + 0.0014

        iframe_with_map = '<iframe width="242" height="200" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://www.openstreetmap.org/export/embed.html?bbox=' + firstlon.to_s  + ',' + firstlat.to_s + ',' + secondlon.to_s + ',' + firstlat.to_s + '&amp;layer=mapnik&amp;marker=' + motion.latitude.to_s + ',' + motion.longitude.to_s + '" style="border: 1px solid black"></iframe>'
   
        # Workaround um ein automatisches Escapen zu vermeiden
        iframe_with_map.html_safe
  end
  
  # Dient zur Anzeiger der Basisinformationen eines Antrags
  def show_basic_information_from_motion(mottion)
    
  end
end

app/views/motions/_form.html.erb
<%= form_for(@motion) do |f| %>
  <% if @motion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@motion.errors.count, "error") %> prohibited this motion from being saved:</h2>

      <ul>
      <% @motion.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title, "Antragstitel:" %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :text, "Antragstext:" %><br />
    <%= f.text_area :text %>
  </div>
  <div class="field">
    <%= f.label :date, "Antragsdatum:" %><br />
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :register, "Aktenzeichen:" %><br />
    <%= f.text_field :register %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/motions/edit.html.erb
<h1>Antrag bearbeiten</h1>

<%= render 'form' %>

<%= link_to 'Show', @motion %> |
<%= link_to 'Zurück zur Übersicht', motions_path %>

app/views/motions/index.html.erb
<h1>Listing motions</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Title</th>
    <th>Text</th>
    <th>Date</th>
    <th>Register</th>
    <th>Latitude</th>
    <th>Longitude</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @motions.each do |motion| %>
  <tr>
    <td><%= motion.id %></td>
    <td><%= motion.title %></td>
    <td><%= motion.text %></td>
    <td><%= motion.date %></td>
    <td><%= motion.register %></td>
    <td><%= motion.latitude %></td>
    <td><%= motion.longitude %></td>
    <td><%= link_to 'Show', motion %></td>
    <td><%= link_to 'Edit', edit_motion_path(motion) %></td>
    <td><%= link_to 'Destroy', motion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
  <tr>
  	<td colspan="10">
  		Tags:<br>
  		<% @tags.each do |tag| %>
  			<%= tag.name %>
  		<% end %>
  	</td>
  </tr>
  <tr>
  	<td colspan="10">
  		Zugeordnete Projekte:<br>
  		<ul>
  		
  		<% @projects = Motion.find(motion.id).projects %>	
  			
  		<% @projects.each do |project| %>
  			<li>
  			<%= project.name %>
  			</li>
  		<% end %>
  		</ul>
  	</td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Motion', new_motion_path %>

app/views/motions/new.html.erb
<h1>Neuer Antrag einfügen</h1>

<%= render 'form' %>

<%= link_to 'Zurück zur Übersicht', motions_path %>

app/views/motions/search.html.erb
<% 
	# Quellcode setzt den Java-Scriptcode für die Anzeige der Marker zusammen. Der Grundaufbau des JavaScript-Codes wurde aus einem CloudMade-Beispiel
	# herausgenommen. Der Ruby-Code ist allerdings eine Eigenentwicklung, was man ihm leider auch ansieht. 
	@motions = Motion.all
	
	markerstring = "var "
	addLayerstring = "map"
	bindPopupstring = ""
	
	@motions.each do |motion|
		markerstring += 'marker' + motion.id.to_s + ' = new L.Marker(new L.LatLng(' + motion.latitude.to_s + ', ' + motion.longitude.to_s + ')), '
		
		bindPopupstring += 'marker' + motion.id.to_s + '.bindPopup("<b>' + motion.title.to_s + '</b><br><a href=\"motions/' + motion.id.to_s + '\">Zeige!</a>"); '
		
		addLayerstring += '.addLayer(marker' + motion.id.to_s + ')'
	end
	
	markerstring = markerstring.chop.chop
	
	markerstring += ';'
	
	addLayerstring += ';'
%>

	<div id="map" style="width: 600px; height: 400px"></div>

	<script src="http://cdn.leafletjs.com/leaflet-0.3.1/leaflet.js"></script>
	<script>
		var map = new L.Map('map');

		var cloudmadeUrl = 'http://{s}.tile.cloudmade.com/BC9A493B41014CAABB98F0471D759707/22677/256/{z}/{x}/{y}.png',
			cloudmadeAttribution = 'Map data &copy; 2011 OpenStreetMap contributors, Imagery &copy; 2011 CloudMade',
			cloudmade = new L.TileLayer(cloudmadeUrl, {maxZoom: 18, attribution: cloudmadeAttribution});

		map.setView(new L.LatLng(50.586, 8.683), 13).addLayer(cloudmade);


		<%=	markerstring.html_safe %>

		<%=	bindPopupstring.html_safe %>

		<%=	addLayerstring.html_safe %>
	</script>

<form class="well form-search" action="/search" method="post">
    <input name="searchstring" type="text" class="input-medium search-query">
    <button type="submit" class="btn">Search</button>
</form>

app/views/motions/searchresult.html.erb
<% @motions = Motion.where("title = ?",params[:searchstring]) %>

<b>Suche nach Anträgen:</b>
<table class="table table-striped">
<% @motions.each do |motion| %>
  <tr>
    <td><%= motion.register %></td>
    <td><%= motion.title %></td>
    <td><%= motion.date.strftime('%d.%m.%Y') %></td>
    <td><%= motion.latitude %></td>
    <td><%= motion.longitude %></td>
    <td><%= link_to 'Details', motion, :class => "btn btn-mini btn-info" %></td>
  </tr>

<% end %>

</table>

app/views/motions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Aktenzeichen:</b><br>
  <%= @motion.register %>
</p>

<p>
  <b>Antragstitel:</b><br>
  <%= @motion.title %>
</p>

<p>
  <b>Antragstext:</b><br>
  <%= @motion.text %>
</p>

<p>
  <b>Antragsdatum:</b><br>
  <%= @motion.date.strftime('%d.%m.%Y') %>
</p>


<p>
  <b>Geodaten:</b><br>
  <%= @motion.latitude %>;&nbsp;<%= @motion.longitude %>
</p>

<p>
  <%= show_motion_on_map (@motion) %>
</p>

<p><b>Tags:</b><br>
 <% @tags.each do |tag| %>
 <%= tag.name %>
 <% end %>
</p>
<p>
  		<b>Zugeordnete Projekte:</b><br>
  		<ul>
  		<% @projects.each do |project| %>
  			<li>
  			<%= project.name %>
  			</li>
  		<% end %>
  		</ul>
  	</td>
  </tr>

<%= link_to 'Bearbeiten', edit_motion_path(@motion) %> |
<%= link_to 'Zurück', motions_path %>

app/views/motions/showonemotion.html.erb
<h1>Antrga mit Verlauf</h1>

<table class="table table-striped"> 
	<% @motion = Motion.find(1) %>

  <tr>
    <td colspan="3"><h2><%= motion.title %></h2></td>
  </tr>
  <tr>
    <td colspan="3"><%= motion.text %></td>
  </tr>
    <tr>		
  		<td>
  			<b>Standort:</b><br /> 
  			<%= show_motion_on_map (motion) %>
  		</td>		
  		<td>
  			<b>Zugeordnete Projekte:</b><br>
  			<%= show_associated_projects(motion) %>
  		</td>
		<td>
  			<b>Zugeordnete Tags:</b></br>		
  			<% @tags = Tag.where("motion_id=?",motion.id) %>
  
  			<% @tags.each do |tag| %>
  			<ul>
    			<%= content_tag_for(:li, tag) do %>
    			<%= tag.name %>
    			<% end %>
    		<%= link_to '', tag, method: :delete, remote: true, :class => "icon icon-trash" %></li>
  			</ul>
			<% end %>
			<%= link_to 'Neues Tag', new_tag_path, :class => "btn btn-success btn-mini" %></td>
  	</tr>
  
  <% @decisions = Decision.where("motion_id=?",motion.id) %>
  
  <% @decisions.each do |decision| %>
  <tr>
  	<td colspan="3">&nbsp;</td>
  </tr>
  <tr>
  	<td  colspan="2"><span style="color:green;"><%= decision.commitee_name %><br>(<%= decision.commitee_date.strftime('%d.%m.%Y') %>)</span></td>
  	<td colspan="1"><%= decision.text %></td>
  </tr>
  
  <% @votes = Vote.where("id=?",decision.vote_id) %>
  <tr>
  	<td colspan="3">Abstimmungsergebnis<br />
  		<% @votes.each do |vote| %>
  		<b>CDU:</b>&nbsp;<%= vote.cdu_party %>&nbsp;&nbsp;<b>SPD:</b>&nbsp;<%= vote.spd_party %>
  		<% end %>
  	</td>
  </tr>
  <% end %>

</table>