config/routes.rb
Antragsportal::Application.routes.draw do
  root :to => 'motions#search'
  
  resources :projects

  resources :votes

  resources :decisions

  resources :tags

  resources :motions
  
  resources :users, only: [:new, :create]
  
  get "/projectmotions/:id" => "projects#projectmotions"
  get "search" => "motions#search"
  post "search" => "motions#searchresult"

  

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_and_belongs_to_many :motions
  attr_accessible :name
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
    
  end
  
  
  
  def projectmotions
      @motions = Project.find(params[:id]).motions.order("date DESC")
    
    
    
    respond_to do |format|
      format.html # showmotions.html.erb
      format.json { render json: @motions }
    end
  end



  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  # Zeigt die zu einem Antrag gehörenden Projekte an
  def show_associated_projects(motion)
      
      htmlstring = "<b>Zugeordnete Projekte:</b><br>"
      
      projects = Motion.find(motion.id).projects 
      
      projects.each do |project|
        htmlstring += '<a href="/projectmotions/' + (project.id).to_s + '">[' + project.name + ']&nbsp;&nbsp;'
      end
        
      htmlstring.html_safe
  end
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, "Projektname:" %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Projekte anzeigen', @project %> |
<%= link_to 'Zurück', projects_path %>

app/views/projects/index.html.erb
<h1>Auflistung aller Projekte</h1>

<table class="table table-striped">
  <tr>
    <th>Projektname:</th>
    <th></th>
    <th></th>
  </tr>
  
  
<% @projects.each do |project| %>
  <tr>
    <td><%= project.name %></td>
    <td><%= link_to 'Bearbeiten', edit_project_path(project), :class => "btn btn-mini"  %></td>
    <td><%= link_to 'Löschen', project, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-mini btn-danger"  %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Neues Projekt', new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/projectmotions.html.erb
<h1>Listet die Anträge </h1>

<table class="table table-striped"> 
  
<% @motions.each do |motion| %>
  <tr>
    <td colspan="3"><h2><%= motion.title %></h2></td>
  </tr>
  <tr>
    <td colspan="3"><%= motion.text %></td>
  </tr>
    <tr>		
  		<td>
  			<b>Standort:</b><br /> 
  			<%= show_motion_on_map (motion) %>
  		</td>		
  		<td>
  			<b>Zugeordnete Projekte:</b><br>
  			<%= show_associated_projects(motion) %>
  		</td>
		<td>
  			<b>Zugeordnete Tags:</b></br>		
  			<% @tags = Tag.where("motion_id=?",motion.id) %>
  			<ul>
  			<% @tags.each do |tag| %>
  			
    			<%= content_tag_for(:li, tag) do %>
    			<%= tag.name %>
    			<% end %>
    		<%= link_to '', tag, method: :delete, remote: true, :class => "icon icon-trash" %></li>
  			
			<% end %>
			</ul>
			<%= link_to 'Neues Tag', new_tag_path, :class => "btn btn-success btn-mini" %></td>
  	</tr>
  
  <% @decisions = Decision.where("motion_id=?",motion.id) %>
  
  <% @decisions.each do |decision| %>
  <tr>
  	<td colspan="3">&nbsp;</td>
  </tr>
  <tr>
  	<td  colspan="2"><span style="color:green;"><%= decision.commitee_name %><br>(<%= decision.commitee_date.strftime('%d.%m.%Y') %>)</span></td>
  	<td colspan="1"><%= decision.text %></td>
  </tr>
  <tr>
  	<td colspan="3"><%= show_votes_by_decision(decision) %>
  </tr>
  <% end %>
  
  <tr>
  	<td colspan="3">&nbsp;</td>
  </tr>
<% end %>
</table>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <b>Name:</b>
  <%= @project.name %>
</p>


<%= link_to 'Bearbeiten', edit_project_path(@project) %> |
<%= link_to 'Zurück zur Übersicht', projects_path %>

app/views/projects/showmotions.html.erb
<h1>Listet die Antraege </h1>

<table>  
  
<% @motions.each do |motion| %>
  <tr>
    <td><h2><%= motion.title %></h2></td>
  </tr>
  <tr>
    <td><%= motion.text %></td>
  </tr>
  <tr>
  <td colspan="10">
  		<b>Zugeordnete Projekte:</b><br>
  		
  		<% @projects = Motion.find(motion.id).projects %>	
  			
  		<% @projects.each do |project| %>
  			<a href="http://localhost:3000/showmotions?projectid=<%= project.id %>">[<%= project.name %>]</a>&nbsp;&nbsp;
  		<% end %>
  	</td>
  	</tr>
  	<tr><td>
  		
  <% @tags = Tag.where("motion_id=?",motion.id) %>
  
  <% @tags.each do |tag| %>
  <ul>
    <li><%= tag.name %>&nbsp;&nbsp;
    <%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></li>
  </ul>
<% end %>
<%= link_to 'New Tag', new_tag_path %></td>
  </tr>
  <% @decisions = Decision.where("motion_id=?",motion.id) %>
  
  <% @decisions.each do |decision| %>
  <tr>
  	<td>&nbsp;</td>
  </tr>
  <tr>
  	<td><span style="color:green;"><%= decision.commitee_name %><br>(<%= decision.commitee_date.strftime('%d.%m.%Y') %>)</span></td>
  	<td colspan="2"><%= decision.text %></td>
  </tr>
  
  <% @votes = Vote.where("id=?",decision.vote_id) %>
  <tr>
  	<td>Abstimmungsergebnis<br />
  		<% @votes.each do |vote| %>
  		<b>CDU:</b>&nbsp;<%= vote.cdu_party %>&nbsp;&nbsp;<b>SPD:</b>&nbsp;<%= vote.spd_party %>
  		<% end %>
  	</td>
  </tr>
  <% end %>
  
  <tr>
  	<td>&nbsp;</td>
  </tr>
<% end %>
</table>